import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.3";

const dbUrl=Deno.env.get("SUPABASE_DB_URL");
const sql=dbUrl?postgres(dbUrl,{prepare:false,max:1}):null;
const TEST_SYMBOL="AAPL";
const CONSENSUS_SYMBOL="IBM";
const MAX_DIV=0.005;

async function sha256Hex(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function secret(name:string){const e=Deno.env.get(name);if(e)return e;try{const r=await sql!`select decrypted_secret from vault.decrypted_secrets where name=${name} limit 1`;return r.length?String(r[0].decrypted_secret):"";}catch{return "";}}
function nyDate(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const o:any={};for(const x of p)o[x.type]=x.value;return `${o.year}-${o.month}-${o.day}`;}
function limitSignal(d:any,status:number){if(status===429)return true;const s=JSON.stringify(d||{}).toLowerCase();return s.includes("rate limit")||s.includes("call frequency")||s.includes("api call frequency");}
async function getJson(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),18000);try{const r=await fetch(url,{signal:c.signal,headers:{"User-Agent":"FWIOS/1.0 provider-validator"}});let d:any={};try{d=await r.json();}catch{d={};}return{ok:r.ok,status:r.status,data:d,rateLimited:limitSignal(d,r.status)};}finally{clearTimeout(t);}}
async function rec(provider:string,scope:string,status:string,opts:any={}){await sql!`insert into fwios.decision_refresh_provider_validation_runs(provider_key,validation_scope,ticker,session_date,status,checks,observed,source_refs,error_text) values(${provider},${scope},${opts.ticker||null},${opts.sessionDate||null},${status},${opts.checks||{}},${opts.observed||{}},${opts.refs||[]},${opts.error||null})`;}
function tdRows(d:any){return Array.isArray(d?.values)?d.values:[];}
function avRows(d:any){return d?.["Time Series (Daily)"]&&typeof d["Time Series (Daily)"]==="object"?d["Time Series (Daily)"]:{};}
function commonSessions(td:any,av:any,endDate:string){const a=avRows(av);const out:any[]=[];for(const r of tdRows(td)){const date=String(r?.datetime||"").slice(0,10);if(!date||date>endDate||!a[date])continue;const p1=Number(r.close),p2=Number(a[date]?.["4. close"]);if(!(p1>0&&p2>0))continue;const div=Math.abs(p1-p2)/((p1+p2)/2);out.push({date,twelve:p1,alpha:p2,div});}return out.sort((x,y)=>y.date.localeCompare(x.date)).slice(0,3);}
function consensusRows(d:any){const rows:any[]=[];const walk=(v:any)=>{if(Array.isArray(v)){for(const x of v)if(x&&typeof x==="object")rows.push(x);}else if(v&&typeof v==="object"){for(const x of Object.values(v))if(Array.isArray(x))walk(x);}};walk(d);return rows;}
function consensusSchemaOk(d:any){const rows=consensusRows(d);return rows.some(r=>{const k=Object.keys(r).map(x=>x.toLowerCase());return k.some(x=>x.includes("eps_estimate")||x.includes("revenue_estimate")||x.includes("analyst_count"))&&(k.includes("horizon")||k.includes("fiscaldateending")||k.includes("fiscal_date_ending"));});}
function consensusFreshOk(d:any){const rows=consensusRows(d);const today=nyDate();return rows.some(r=>{const h=String(r.horizon||r.Horizon||"").toLowerCase();const f=String(r.fiscalDateEnding||r.fiscal_date_ending||"").slice(0,10);return h.includes("next")||(f&&f>=today);});}
async function markState(key:string,secretPresent:boolean){if(!secretPresent){await sql!`update fwios.decision_refresh_provider_registry set active=false,readiness_status='NOT_CONFIGURED',source_tier='A_PENDING_VALIDATION',updated_at=now() where provider_key=${key}`;}else{await sql!`update fwios.decision_refresh_provider_registry set readiness_status=case when readiness_status='READY' then 'READY' else 'DEGRADED' end,updated_at=now() where provider_key=${key}`;}}
async function promote(key:string){const r=await sql!`select fwios.apply_decision_refresh_provider_promotion(${key}) as gate`;return r[0]?.gate||{};}

Deno.serve(async(req:Request)=>{
 if(!sql||!dbUrl)return Response.json({error:"DB_UNAVAILABLE"},{status:503});
 if(req.method!=="POST")return new Response("Method Not Allowed",{status:405});
 const tok=req.headers.get("x-fwios-automation-token")||"";if(tok.length<32)return new Response("Unauthorized",{status:401});
 const a=await sql`select token_sha256 from fwios.decision_refresh_automation_access where access_key='DECISION_REFRESH_WORKER' and active=true limit 1`;if(!a.length||!safeEqual(await sha256Hex(tok),String(a[0].token_sha256)))return new Response("Unauthorized",{status:401});
 const force=(await req.json().catch(()=>({})))?.force===true;
 const tdKey=await secret("TWELVE_DATA_API_KEY"), avKey=await secret("ALPHA_VANTAGE_API_KEY");
 await markState("TWELVE_DATA",!!tdKey); await markState("ALPHA_VANTAGE",!!avKey);
 if(!tdKey&&!avKey){await sql`update fwios.system_state set state_value=state_value||${{provider_validator_last_status:"BLOCKED_KEYS_MISSING",provider_validator_last_run:new Date().toISOString()}},as_of_text=${new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Bangkok",dateStyle:"short",timeStyle:"short"}).format(new Date())+" Asia/Bangkok"},updated_at=now() where state_key='auto_decision_refresh_v1'`;return Response.json({ok:true,status:"BLOCKED_KEYS_MISSING",twelve_data:false,alpha_vantage:false});}
 const last=await sql`select max(created_at) as ts from fwios.decision_refresh_provider_validation_runs where validation_scope<>'DOCUMENTATION_CONTRACT'`;
 if(!force&&last[0]?.ts&&Date.now()-new Date(last[0].ts).getTime()<6*3600*1000){return Response.json({ok:true,status:"SKIPPED_COOLDOWN",next_after_hours:6});}
 const end=nyDate(); let td:any=null,av:any=null,cons:any=null; let tdRate=false,avRate=false;
 if(tdKey){const url=`https://api.twelvedata.com/time_series?symbol=${TEST_SYMBOL}&interval=1day&outputsize=10&end_date=${end}&adjust=none&apikey=${encodeURIComponent(tdKey)}`;const r=await getJson(url);td=r.data;tdRate=r.rateLimited;const live=r.ok&&!r.rateLimited&&td?.status!=="error";await rec("TWELVE_DATA","LIVE_CONNECTIVITY",live?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{http_status:r.status,no_rate_limit:!r.rateLimited},observed:{status:td?.status||null},refs:["https://api.twelvedata.com/time_series"],error:live?null:JSON.stringify(td).slice(0,500)});const meta=td?.meta||{};const schema=live&&Array.isArray(td?.values)&&td.values.length>=3&&["symbol","currency","exchange","exchange_timezone"].every(k=>!!meta[k])&&td.values.every((x:any)=>Number(x?.close)>0);await rec("TWELVE_DATA","RESPONSE_SCHEMA",schema?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{required_meta:true,values_min_3:true,positive_close:true},observed:{meta,rows:tdRows(td).length},refs:["https://api.twelvedata.com/time_series"]});}
 if(avKey){const purl=`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${TEST_SYMBOL}&outputsize=compact&apikey=${encodeURIComponent(avKey)}`;const pr=await getJson(purl);av=pr.data;avRate=pr.rateLimited;const live=pr.ok&&!pr.rateLimited&&!av?.["Error Message"]&&!av?.Information&&!av?.Note;await rec("ALPHA_VANTAGE","LIVE_CONNECTIVITY",live?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{http_status:pr.status,no_rate_limit:!pr.rateLimited},observed:{keys:Object.keys(av||{}).slice(0,10)},refs:["https://www.alphavantage.co/query?function=TIME_SERIES_DAILY"],error:live?null:JSON.stringify(av).slice(0,500)});const ar=avRows(av), schema=live&&Object.keys(ar).length>=3&&Object.values(ar).slice(0,3).every((x:any)=>Number(x?.["4. close"])>0);await rec("ALPHA_VANTAGE","RESPONSE_SCHEMA",schema?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{series_key:true,rows_min_3:true,positive_close:true},observed:{rows:Object.keys(ar).length},refs:["https://www.alphavantage.co/query?function=TIME_SERIES_DAILY"]});const curl=`https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES&symbol=${CONSENSUS_SYMBOL}&apikey=${encodeURIComponent(avKey)}`;const cr=await getJson(curl);cons=cr.data;avRate=avRate||cr.rateLimited;const cs=!cr.rateLimited&&cr.ok&&!cons?.Information&&!cons?.Note&&!cons?.["Error Message"]&&consensusSchemaOk(cons);const cf=cs&&consensusFreshOk(cons);await rec("ALPHA_VANTAGE","CONSENSUS_SCHEMA",cs?"PASS":"FAIL",{ticker:CONSENSUS_SYMBOL,checks:{estimate_fields:true,horizon_or_fiscal_period:true},observed:{top_keys:Object.keys(cons||{}).slice(0,20),rows:consensusRows(cons).length},refs:["https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES"],error:cs?null:JSON.stringify(cons).slice(0,500)});await rec("ALPHA_VANTAGE","CONSENSUS_FRESHNESS",cf?"PASS":"FAIL",{ticker:CONSENSUS_SYMBOL,checks:{forward_horizon_or_future_fiscal_period:true},observed:{rows:consensusRows(cons).length},refs:["https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES"]});}
 if(tdKey&&avKey&&td&&av){const cs=commonSessions(td,av,end);for(const x of cs){const st=x.div<=MAX_DIV?"PASS":"FAIL";const o={twelve_close:x.twelve,alpha_close:x.alpha,divergence_pct:x.div,max_divergence_pct:MAX_DIV};await rec("TWELVE_DATA","PRICE_CROSSCHECK",st,{ticker:TEST_SYMBOL,sessionDate:x.date,checks:{common_session:true,divergence_lte_0_5pct:x.div<=MAX_DIV},observed:o,refs:["https://api.twelvedata.com/time_series","https://www.alphavantage.co/query?function=TIME_SERIES_DAILY"]});await rec("ALPHA_VANTAGE","PRICE_CROSSCHECK",st,{ticker:TEST_SYMBOL,sessionDate:x.date,checks:{common_session:true,divergence_lte_0_5pct:x.div<=MAX_DIV},observed:o,refs:["https://api.twelvedata.com/time_series","https://www.alphavantage.co/query?function=TIME_SERIES_DAILY"]});}const all=cs.length>=3&&cs.every(x=>x.div<=MAX_DIV), tz=String(td?.meta?.exchange_timezone||"");await rec("TWELVE_DATA","SESSION_SEMANTICS",all&&!!tz?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{three_common_sessions:cs.length>=3,exchange_timezone_present:!!tz},observed:{sessions:cs.map(x=>x.date),exchange_timezone:tz}});await rec("ALPHA_VANTAGE","SESSION_SEMANTICS",all?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{three_dates_match_twelve_exchange_sessions:all},observed:{sessions:cs.map(x=>x.date)}});await rec("TWELVE_DATA","ADJUSTMENT_SEMANTICS",all?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{request_adjust:"none",three_raw_close_matches:all},observed:{sessions:cs}});await rec("ALPHA_VANTAGE","ADJUSTMENT_SEMANTICS",all?"PASS":"FAIL",{ticker:TEST_SYMBOL,checks:{endpoint_semantics:"raw_as_traded_daily",three_raw_close_matches:all},observed:{sessions:cs}});}
 if(tdKey)await rec("TWELVE_DATA","RATE_LIMIT",tdRate?"FAIL":"PASS",{ticker:TEST_SYMBOL,checks:{no_rate_limit_signal:!tdRate}});
 if(avKey)await rec("ALPHA_VANTAGE","RATE_LIMIT",avRate?"FAIL":"PASS",{ticker:TEST_SYMBOL,checks:{no_rate_limit_signal:!avRate}});
 const tdGate=await promote("TWELVE_DATA"), avGate=await promote("ALPHA_VANTAGE");
 const status=tdGate?.eligible&&avGate?.eligible?"PROVIDERS_READY":"VALIDATION_INCOMPLETE";
 await sql`update fwios.system_state set state_value=state_value||${{provider_validator_last_status:status,provider_validator_last_run:new Date().toISOString(),twelve_data_gate:tdGate,alpha_vantage_gate:avGate}},updated_at=now() where state_key='auto_decision_refresh_v1'`;
 return Response.json({ok:true,status,twelve_data:tdGate,alpha_vantage:avGate,mode:"SHADOW",authoritative_write:false});
});
