import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.3";
const dbUrl=Deno.env.get("SUPABASE_DB_URL"); const sql=dbUrl?postgres(dbUrl,{prepare:false,max:1}):null; const TEST="AAPL",CONS="IBM",MAX=0.005; let lastAlphaCall=0;
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('');} function eq(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function secret(n:string){const e=Deno.env.get(n);if(e)return e;try{const r=await sql!`select decrypted_secret from vault.decrypted_secrets where name=${n} limit 1`;return r.length?String(r[0].decrypted_secret):'';}catch{return '';}}
function ny(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),o:any={};for(const x of p)o[x.type]=x.value;return `${o.year}-${o.month}-${o.day}`;}
function limited(d:any,s:number){if(s===429)return true;const x=JSON.stringify(d||{}).toLowerCase();return x.includes('rate limit')||x.includes('call frequency')||x.includes('25 requests per day')||x.includes('premium plans');}
async function throttleAlpha(){const wait=1100-(Date.now()-lastAlphaCall);if(wait>0)await new Promise(r=>setTimeout(r,wait));lastAlphaCall=Date.now();}
async function get(url:string){if(url.includes('alphavantage.co'))await throttleAlpha();const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'FWIOS/1.0 provider-validator'}});let d:any={};try{d=await r.json();}catch{}return{ok:r.ok,status:r.status,data:d,rate:limited(d,r.status)};}finally{clearTimeout(t);}}
async function rec(p:string,s:string,st:string,o:any={}){await sql!`insert into fwios.decision_refresh_provider_validation_runs(provider_key,validation_scope,ticker,session_date,status,checks,observed,source_refs,error_text) values(${p},${s},${o.ticker||null},${o.date||null},${st},${o.checks||{}},${o.observed||{}},${o.refs||[]},${o.error||null})`;}
function tdRows(d:any){return Array.isArray(d?.values)?d.values:[];} function avRows(d:any){return d?.['Time Series (Daily)']&&typeof d['Time Series (Daily)']==='object'?d['Time Series (Daily)']:{};}
function commons(td:any,av:any,end:string){const a=avRows(av),out:any[]=[];for(const r of tdRows(td)){const d=String(r.datetime||'').slice(0,10);if(!d||d>end||!a[d])continue;const x=Number(r.close),y=Number(a[d]?.['4. close']);if(x>0&&y>0)out.push({date:d,twelve:x,alpha:y,div:Math.abs(x-y)/((x+y)/2)});}return out.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);}
function consRows(d:any){const out:any[]=[];const walk=(v:any)=>{if(Array.isArray(v)){for(const x of v)if(x&&typeof x==='object')out.push(x);}else if(v&&typeof v==='object')for(const x of Object.values(v))if(Array.isArray(x))walk(x);};walk(d);return out;}
function consSchema(d:any){return consRows(d).some(r=>{const k=Object.keys(r).map(x=>x.toLowerCase());return k.some(x=>x.includes('eps_estimate')||x.includes('revenue_estimate')||x.includes('analyst_count'))&&(k.includes('horizon')||k.includes('fiscaldateending')||k.includes('fiscal_date_ending'));});}
function consFresh(d:any){const today=ny();return consRows(d).some(r=>String(r.horizon||r.Horizon||'').toLowerCase().includes('next')||String(r.fiscalDateEnding||r.fiscal_date_ending||'').slice(0,10)>=today);}
async function mark(k:string,has:boolean){await sql!`update fwios.decision_refresh_provider_registry set active=case when ${has} then active else false end,readiness_status=case when ${has} then case when readiness_status='READY' then 'READY' else 'DEGRADED' end else 'NOT_CONFIGURED' end,source_tier=case when ${has} then source_tier else 'A_PENDING_VALIDATION' end,updated_at=now() where provider_key=${k}`;}
async function promote(k:string){const r=await sql!`select fwios.apply_decision_refresh_provider_promotion(${k}) gate`;return r[0]?.gate||{};}
Deno.serve(async(req:Request)=>{if(!sql)return Response.json({error:'DB_UNAVAILABLE'},{status:503});if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});const tok=req.headers.get('x-fwios-automation-token')||'',a=await sql`select token_sha256 from fwios.decision_refresh_automation_access where access_key='DECISION_REFRESH_WORKER' and active=true limit 1`;if(tok.length<32||!a.length||!eq(await sha(tok),String(a[0].token_sha256)))return new Response('Unauthorized',{status:401});const body=await req.json().catch(()=>({})),force=body?.force===true,tdKey=await secret('TWELVE_DATA_API_KEY'),avKey=await secret('ALPHA_VANTAGE_API_KEY');await mark('TWELVE_DATA',!!tdKey);await mark('ALPHA_VANTAGE_PRICE',!!avKey);await mark('ALPHA_VANTAGE_CONSENSUS',!!avKey);if(!tdKey&&!avKey)return Response.json({ok:true,status:'BLOCKED_KEYS_MISSING'});
const last=await sql`select max(created_at) ts from fwios.decision_refresh_provider_validation_runs where provider_key in ('TWELVE_DATA','ALPHA_VANTAGE_PRICE','ALPHA_VANTAGE_CONSENSUS') and validation_scope<>'DOCUMENTATION_CONTRACT'`;if(!force&&last[0]?.ts&&Date.now()-new Date(last[0].ts).getTime()<6*3600*1000)return Response.json({ok:true,status:'SKIPPED_COOLDOWN'});
const end=ny();let td:any=null,av:any=null;let tdRate=false,avPriceRate=false,avConsRate=false;
if(tdKey){const r=await get(`https://api.twelvedata.com/time_series?symbol=${TEST}&interval=1day&outputsize=10&end_date=${end}&adjust=none&apikey=${encodeURIComponent(tdKey)}`);td=r.data;tdRate=r.rate;const live=r.ok&&!r.rate&&td?.status!=='error',schema=live&&tdRows(td).length>=3&&['symbol','currency','exchange','exchange_timezone'].every(k=>!!td?.meta?.[k]);await rec('TWELVE_DATA','LIVE_CONNECTIVITY',live?'PASS':'FAIL',{ticker:TEST,checks:{http_status:r.status,no_rate_limit:!r.rate}});await rec('TWELVE_DATA','RESPONSE_SCHEMA',schema?'PASS':'FAIL',{ticker:TEST,checks:{rows_min_3:true,required_meta:true}});}
if(avKey){const pr=await get(`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${TEST}&outputsize=compact&apikey=${encodeURIComponent(avKey)}`);av=pr.data;avPriceRate=pr.rate;const live=pr.ok&&!pr.rate&&!av?.Information&&!av?.Note&&!av?.['Error Message'],schema=live&&Object.keys(avRows(av)).length>=3;await rec('ALPHA_VANTAGE_PRICE','LIVE_CONNECTIVITY',live?'PASS':'FAIL',{ticker:TEST,checks:{http_status:pr.status,no_rate_limit:!pr.rate}});await rec('ALPHA_VANTAGE_PRICE','RESPONSE_SCHEMA',schema?'PASS':'FAIL',{ticker:TEST,checks:{rows_min_3:true,series_key:true}});const cr=await get(`https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES&symbol=${CONS}&apikey=${encodeURIComponent(avKey)}`),d=cr.data;avConsRate=cr.rate;const cs=cr.ok&&!cr.rate&&!d?.Information&&!d?.Note&&!d?.['Error Message']&&consSchema(d),cf=cs&&consFresh(d);await rec('ALPHA_VANTAGE_CONSENSUS','CONSENSUS_SCHEMA',cs?'PASS':'FAIL',{ticker:CONS,checks:{schema:true},error:cs?null:JSON.stringify(d).slice(0,500)});await rec('ALPHA_VANTAGE_CONSENSUS','CONSENSUS_FRESHNESS',cf?'PASS':'FAIL',{ticker:CONS,checks:{forward_or_future:true}});}
if(tdKey&&avKey&&td&&av){const cs=commons(td,av,end),all=cs.length>=3&&cs.every(x=>x.div<=MAX),tz=String(td?.meta?.exchange_timezone||'');for(const x of cs){const st=x.div<=MAX?'PASS':'FAIL',obs={twelve_close:x.twelve,alpha_close:x.alpha,divergence_pct:x.div};await rec('TWELVE_DATA','PRICE_CROSSCHECK',st,{ticker:TEST,date:x.date,observed:obs});await rec('ALPHA_VANTAGE_PRICE','PRICE_CROSSCHECK',st,{ticker:TEST,date:x.date,observed:obs});}await rec('TWELVE_DATA','SESSION_SEMANTICS',all&&!!tz?'PASS':'FAIL',{ticker:TEST,observed:{sessions:cs.map(x=>x.date),exchange_timezone:tz}});await rec('ALPHA_VANTAGE_PRICE','SESSION_SEMANTICS',all?'PASS':'FAIL',{ticker:TEST,observed:{sessions:cs.map(x=>x.date)}});await rec('TWELVE_DATA','ADJUSTMENT_SEMANTICS',all?'PASS':'FAIL',{ticker:TEST,checks:{adjust:'none'}});await rec('ALPHA_VANTAGE_PRICE','ADJUSTMENT_SEMANTICS',all?'PASS':'FAIL',{ticker:TEST,checks:{semantics:'raw_as_traded_daily'}});}
if(tdKey)await rec('TWELVE_DATA','RATE_LIMIT',tdRate?'FAIL':'PASS',{ticker:TEST,checks:{no_rate_limit_signal:!tdRate}});if(avKey){await rec('ALPHA_VANTAGE_PRICE','RATE_LIMIT',avPriceRate?'FAIL':'PASS',{ticker:TEST,checks:{no_rate_limit_signal:!avPriceRate,min_interval_ms:1100}});await rec('ALPHA_VANTAGE_CONSENSUS','RATE_LIMIT',avConsRate?'FAIL':'PASS',{ticker:CONS,checks:{no_rate_limit_signal:!avConsRate,min_interval_ms:1100}});}
const tg=await promote('TWELVE_DATA'),pg=await promote('ALPHA_VANTAGE_PRICE'),cg=await promote('ALPHA_VANTAGE_CONSENSUS'),status=tg?.eligible&&pg?.eligible?'PRICE_PROVIDERS_READY':'VALIDATION_INCOMPLETE';await sql`update fwios.system_state set state_value=state_value||${{provider_validator_last_status:status,provider_validator_last_run:new Date().toISOString(),twelve_data_gate:tg,alpha_price_gate:pg,alpha_consensus_gate:cg,provider_capability_split:'V1_LIVE',alpha_min_interval_ms:1100}},updated_at=now() where state_key='auto_decision_refresh_v1'`;return Response.json({ok:true,status,twelve_data:tg,alpha_price:pg,alpha_consensus:cg,mode:'SHADOW',authoritative_write:false,version:3,alpha_min_interval_ms:1100});});
