import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.3";
const dbUrl=Deno.env.get("SUPABASE_DB_URL"); const sql=dbUrl?postgres(dbUrl,{prepare:false,max:1}):null; const QUEUE="fwios_decision_refresh"; const SEC_UA=Deno.env.get("SEC_USER_AGENT")||"FWIOS/1.0 personal-investment-research"; let tickerMap:Map<string,string>|null=null; let lastAlphaCall=0;
async function sha256Hex(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function dateOnly(v:any){if(v instanceof Date)return v.toISOString().slice(0,10);const s=String(v??'');const m=s.match(/\d{4}-\d{2}-\d{2}/);if(m)return m[0];const d=new Date(v);if(Number.isNaN(d.getTime()))throw new Error('INVALID_SESSION_DATE');return d.toISOString().slice(0,10);}
async function throttleAlpha(){const wait=1100-(Date.now()-lastAlphaCall);if(wait>0)await new Promise(r=>setTimeout(r,wait));lastAlphaCall=Date.now();}
function sourceLabel(url:string){return url.includes('twelvedata.com')?'TWELVE_DATA':url.includes('alphavantage.co')?'ALPHA_VANTAGE':url.includes('sec.gov')?'SEC':'HTTP';}
async function fetchJson(url:string,headers:Record<string,string>={}){if(url.includes('alphavantage.co'))await throttleAlpha();const c=new AbortController(),t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{headers,signal:c.signal});const text=await r.text();let d:any=text;try{d=JSON.parse(text);}catch{}if(!r.ok)throw new Error(`${sourceLabel(url)}_HTTP_${r.status}_${typeof d==='string'?d.slice(0,180):JSON.stringify(d).slice(0,180)}`);return d;}finally{clearTimeout(t);}}
async function providerState(key:string){const r=await sql!`select active,readiness_status,source_tier,secret_name,config from fwios.decision_refresh_provider_registry where provider_key=${key} limit 1`;return r[0]??null;}
function approved(p:any){return !!p&&p.active===true&&p.readiness_status==='READY'&&p.source_tier==='A';}
async function secret(name:string|null|undefined){if(!name)return null;const e=Deno.env.get(name);if(e)return e;try{const r=await sql!`select decrypted_secret from vault.decrypted_secrets where name=${name} limit 1`;return r.length?String(r[0].decrypted_secret):null;}catch{return null;}}
async function reserveAlpha(endpointClass:string,capability:string,job:any){const r=await sql!`select fwios.reserve_decision_refresh_api_call_v1('ALPHA_VANTAGE_SHARED',${capability},${endpointClass},'decision-refresh-worker-v1',${job?.job_id??null}::uuid,${{ticker:job?.ticker??null,job_type:job?.job_type??null}}::jsonb) gate`;return r[0]?.gate||{allowed:false,reason:'QUOTA_RESERVATION_FAILED'};}
async function put(job:any,factClass:string,provider:string,url:string,payload:any){const fp=await sha256Hex(JSON.stringify(payload));await sql!`insert into fwios.decision_refresh_shadow_evidence(run_id,job_id,ticker,fact_class,source_provider,source_url,source_tier,observed_at,payload_fingerprint,payload,collection_status) values(${job.run_id},${job.job_id},${job.ticker},${factClass},${provider},${url},'A',now(),${fp},${payload},'PASS') on conflict(job_id,source_provider,fact_class) do update set observed_at=excluded.observed_at,payload_fingerprint=excluded.payload_fingerprint,payload=excluded.payload,collection_status='PASS'`;}
async function secMap(){if(tickerMap)return tickerMap;const d=await fetchJson("https://www.sec.gov/files/company_tickers.json",{"User-Agent":SEC_UA,"Accept-Encoding":"gzip, deflate"});const m=new Map<string,string>();for(const v of Object.values(d as Record<string,any>)){if(v?.ticker&&v?.cik_str!=null)m.set(String(v.ticker).toUpperCase(),String(v.cik_str).padStart(10,"0"));}tickerMap=m;return m;}
function compactFacts(d:any){const g=d?.facts?.['us-gaap']||{},tags=['Revenues','RevenueFromContractWithCustomerExcludingAssessedTax','SalesRevenueNet','NetIncomeLoss','NetCashProvidedByUsedInOperatingActivities','PaymentsToAcquirePropertyPlantAndEquipment','CashAndCashEquivalentsAtCarryingValue','LongTermDebtCurrent','LongTermDebtNoncurrent','ShareBasedCompensation','WeightedAverageNumberOfDilutedSharesOutstanding','EarningsPerShareDiluted'],out:any={};for(const tag of tags){const f=g[tag];if(!f?.units)continue;out[tag]={label:f.label,units:Object.fromEntries(Object.entries(f.units).map(([u,rows]:any)=>[u,rows.slice().sort((a:any,b:any)=>String(b.filed||'').localeCompare(String(a.filed||''))).slice(0,12)]))};}return{entity_name:d?.entityName??null,cik:d?.cik??null,facts:out};}
async function processSec(job:any){const m=await secMap(),cik=m.get(String(job.ticker).toUpperCase());if(!cik)return{status:'BLOCKED',reason:'SEC_CIK_NOT_FOUND'};const h={"User-Agent":SEC_UA,"Accept-Encoding":"gzip, deflate"},su=`https://data.sec.gov/submissions/CIK${cik}.json`,fu=`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`;const [d,cf]=await Promise.all([fetchJson(su,h),fetchJson(fu,h)]);const r=d?.filings?.recent||{},forms=Array.isArray(r.form)?r.form:[],allowed=new Set(['10-K','10-Q','8-K','20-F','40-F','6-K']),filings:any[]=[];for(let i=0;i<forms.length&&filings.length<30;i++)if(allowed.has(String(forms[i])))filings.push({form:forms[i],accession_number:r.accessionNumber?.[i],filing_date:r.filingDate?.[i],report_date:r.reportDate?.[i],accepted_at:r.acceptanceDateTime?.[i],primary_document:r.primaryDocument?.[i],items:r.items?.[i]});await put(job,'SEC_SUBMISSIONS','SEC_EDGAR',su,{cik,entity_name:d?.name??null,latest_filings:filings});const f=compactFacts(cf);await put(job,'SEC_COMPANY_FACTS','SEC_EDGAR',fu,f);return{status:'PASS',cik,companyfacts_tag_count:Object.keys(f.facts||{}).length};}
function exactPair(td:any,av:any,sessionDate:string){const tdRows=Array.isArray(td?.values)?td.values:[];const avRows=av?.['Time Series (Daily)']||{};const tdExact=tdRows.find((r:any)=>String(r?.datetime||'').slice(0,10)===sessionDate);const avExact=avRows?.[sessionDate];const tdDates=tdRows.map((r:any)=>String(r?.datetime||'').slice(0,10)).filter(Boolean).sort().reverse();const avDates=Object.keys(avRows).sort().reverse();const availability={twelve_latest_date:tdDates[0]||null,alpha_latest_date:avDates[0]||null,requested_session_date:sessionDate};if(!tdExact||!avExact)return{exact:null,availability};const p1=Number(tdExact.close),p2=Number(avExact?.['4. close']);if(!(p1>0&&p2>0))return{exact:null,availability};return{exact:{date:sessionDate,twelve:p1,alpha:p2,meta:td.meta??{}},availability};}
async function processPrice(job:any){
  const av=await providerState('ALPHA_VANTAGE_PRICE'),ak=await secret(av?.secret_name);
  if(!ak||!approved(av))return{status:'BLOCKED',reason:'BLOCKED_ALPHA_PRICE_PROVIDER_NOT_APPROVED',alpha_price:av};
  const sd=dateOnly(job.session_date);
  const primaryRows=await sql!`select asset_symbol,session_date,close_price,currency,exchange,primary_provider,source_url,source_tier,retrieved_at,provenance_status
    from fwios.market_daily_closes where asset_symbol=${job.ticker} and session_date=${sd}::date and provenance_status='PASS' limit 1`;
  if(!primaryRows.length)return{status:'BLOCKED',reason:'PRIMARY_DAILY_CLOSE_NOT_READY',requested_session_date:sd,primary_provider:'TWELVE_DATA'};
  const primary:any=primaryRows[0];
  const quota=await reserveAlpha('PRICE','PRICE',job);
  if(!quota?.allowed)return{status:'BLOCKED',reason:'ALPHA_DAILY_QUOTA_BUDGET_EXHAUSTED',quota};
  const au=`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${encodeURIComponent(job.ticker)}&outputsize=compact&apikey=${encodeURIComponent(ak)}`;
  const a=await fetchJson(au);
  if(a?.Note||a?.Information||a?.['Error Message'])throw new Error(`ALPHA_PRICE_API_${String(a?.Information||a?.Note||a?.['Error Message']).slice(0,180)}`);
  const avRows=(a?.['Time Series (Daily)']&&typeof a['Time Series (Daily)']==='object')?a['Time Series (Daily)']:{},ar=avRows?.[sd];
  if(!ar)return{status:'BLOCKED',reason:'ALPHA_EXACT_SESSION_NOT_AVAILABLE',requested_session_date:sd,alpha_latest_date:Object.keys(avRows).sort().reverse()[0]||null,quota};
  const p1=Number(primary.close_price),p2=Number(ar?.['4. close']);
  if(!(p1>0&&p2>0))return{status:'BLOCKED',reason:'INVALID_PRICE',quota};
  const div=Math.abs(p1-p2)/((p1+p2)/2);
  await put(job,'MARKET_PRICE','TWELVE_DATA',String(primary.source_url||'https://api.twelvedata.com/time_series'),{
    session_date:sd,close:p1,source:'fwios.market_daily_closes',retrieved_at:primary.retrieved_at,
    currency:primary.currency,exchange:primary.exchange,exact_session:true
  });
  await put(job,'MARKET_PRICE','ALPHA_VANTAGE_PRICE','https://www.alphavantage.co/query?function=TIME_SERIES_DAILY',{
    session_date:sd,close:p2,semantics:'raw_as_traded',exact_session:true
  });
  if(div>0.005){
    await sql!`update fwios.market_daily_closes set verification_status='CONFLICT',secondary_provider='ALPHA_VANTAGE_PRICE',
      secondary_close=${p2},divergence_pct=${div},verified_at=now(),updated_at=now()
      where asset_symbol=${job.ticker} and session_date=${sd}::date`;
    return{status:'BLOCKED',reason:'PRICE_CONFLICT',session_date:sd,divergence_pct:div,twelve:p1,alpha:p2,quota};
  }
  await sql!`update fwios.market_daily_closes set verification_status='VERIFIED',secondary_provider='ALPHA_VANTAGE_PRICE',
    secondary_close=${p2},divergence_pct=${div},verified_at=now(),updated_at=now()
    where asset_symbol=${job.ticker} and session_date=${sd}::date`;
  return{status:'PASS',session_date:sd,divergence_pct:div,selected_price:(p1+p2)/2,twelve:p1,alpha:p2,
    exact_session:true,quota,primary_store:'fwios.market_daily_closes',verification_scope:'SELECTIVE'};
}
async function processConsensus(job:any){const av=await providerState('ALPHA_VANTAGE_CONSENSUS'),k=await secret(av?.secret_name);if(!k||!approved(av))return{status:'BLOCKED',reason:'BLOCKED_CONSENSUS_PROVIDER_NOT_APPROVED',alpha_consensus:av};const quota=await reserveAlpha('RESERVE','CONSENSUS',job);if(!quota?.allowed)return{status:'BLOCKED',reason:'ALPHA_RESERVE_QUOTA_EXHAUSTED',quota};const u=`https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES&symbol=${encodeURIComponent(job.ticker)}&apikey=${encodeURIComponent(k)}`,d=await fetchJson(u);if(d?.Note||d?.Information||d?.['Error Message'])throw new Error('ALPHA_CONSENSUS_LIMIT_OR_ERROR');await put(job,'ANALYST_CONSENSUS','ALPHA_VANTAGE_CONSENSUS','https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES',d);return{status:'PASS',provider:'ALPHA_VANTAGE_CONSENSUS',quota};}
async function handle(j:any){if(j.job_type==='SEC_SUBMISSIONS')return processSec(j);if(j.job_type==='PRICE_PAIR')return processPrice(j);if(j.job_type==='CONSENSUS')return processConsensus(j);return{status:'BLOCKED',reason:'UNKNOWN_JOB_TYPE'};}
async function ack(id:any){await sql!`select pgmq.delete(${QUEUE}::text,${id}::bigint)`;} async function archive(id:any){await sql!`select pgmq.archive(${QUEUE}::text,${id}::bigint)`;}
Deno.serve(async(req:Request)=>{if(!sql||!dbUrl)return Response.json({error:'DB_UNAVAILABLE'},{status:503});if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});const tok=req.headers.get('x-fwios-automation-token')||'',x=await sql`select token_sha256 from fwios.decision_refresh_automation_access where access_key='DECISION_REFRESH_WORKER' and active=true limit 1`;if(tok.length<32||!x.length||!safeEqual(await sha256Hex(tok),String(x[0].token_sha256)))return new Response('Unauthorized',{status:401});const msgs=await sql`select * from pgmq.read(${QUEUE}::text,300::integer,10::integer)`;let passed=0,blocked=0,retried=0,dead=0;const touched=new Set<string>();for(const m of msgs){const id=m?.message?.job_id;if(!id){await ack(m.msg_id);continue;}const rs=await sql`select j.*,r.session_date from fwios.decision_refresh_jobs j join fwios.decision_refresh_runs r on r.run_id=j.run_id where j.job_id=${id}::uuid limit 1`;if(!rs.length){await ack(m.msg_id);continue;}const j:any=rs[0];touched.add(String(j.run_id));if(['PASS','BLOCKED','DEAD_LETTER'].includes(String(j.status))){await ack(m.msg_id);continue;}const attempt=Number(j.attempts||0)+1;await sql`update fwios.decision_refresh_jobs set status='RUNNING',attempts=${attempt},updated_at=now() where job_id=${j.job_id}::uuid`;try{const r:any=await handle(j);if(r.status==='PASS'){await sql`update fwios.decision_refresh_jobs set status='PASS',output=${r},last_error=null,completed_at=now(),updated_at=now() where job_id=${j.job_id}::uuid`;passed++;}else{await sql`update fwios.decision_refresh_jobs set status='BLOCKED',output=${r},last_error=${r.reason||null},completed_at=now(),updated_at=now() where job_id=${j.job_id}::uuid`;blocked++;}await ack(m.msg_id);}catch(e){const er=e instanceof Error?e.message:String(e);if(attempt>=Number(j.max_attempts||5)){await sql`update fwios.decision_refresh_jobs set status='DEAD_LETTER',last_error=${er},completed_at=now(),updated_at=now() where job_id=${j.job_id}::uuid`;await archive(m.msg_id);dead++;}else{await sql`update fwios.decision_refresh_jobs set status='RETRY',last_error=${er},updated_at=now() where job_id=${j.job_id}::uuid`;retried++;}}}for(const rid of touched)await sql`select fwios.refresh_decision_refresh_run_status(${rid}::uuid)`;return Response.json({ok:true,worker:'decision-refresh-worker-v1',version:14,read:msgs.length,passed,blocked,retried,dead,mode:'SHADOW',authoritative_write:false,capability_split:'DAILY_CLOSE_PRIMARY_SELECTIVE_ALPHA_VERIFY_V1',alpha_min_interval_ms:1100,exact_session_required:true,daily_close_primary:'TWELVE_DATA_DB_STORE',quota_guard:'ALPHA_25_PER_DAY_PRICE15_VALIDATOR2_RESERVE3'});});
