import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import postgres from "npm:postgres@3.4.3";

const dbUrl = Deno.env.get("SUPABASE_DB_URL");
const sql = dbUrl ? postgres(dbUrl, { prepare:false, max:1 }) : null;
const QUEUE = "fwios_decision_refresh";
const SEC_UA = Deno.env.get("SEC_USER_AGENT") || "FWIOS/1.0 personal-investment-research";
let tickerMap: Map<string,string> | null = null;

async function sha256Hex(s:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,"0")).join("");}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
async function fetchJson(url:string,headers:Record<string,string>={}){const c=new AbortController();const t=setTimeout(()=>c.abort(),15000);try{const r=await fetch(url,{headers,signal:c.signal});if(!r.ok)throw new Error(`HTTP_${r.status}`);return await r.json();}finally{clearTimeout(t);}}
async function secMap(){if(tickerMap)return tickerMap;const d=await fetchJson("https://www.sec.gov/files/company_tickers.json",{"User-Agent":SEC_UA,"Accept-Encoding":"gzip, deflate"});const m=new Map<string,string>();for(const v of Object.values(d as Record<string,any>)){if(v?.ticker&&v?.cik_str!=null)m.set(String(v.ticker).toUpperCase(),String(v.cik_str).padStart(10,"0"));}tickerMap=m;return m;}
async function providerState(key:string){const r=await sql!`select active,readiness_status,source_tier,secret_name,config from fwios.decision_refresh_provider_registry where provider_key=${key} limit 1`;return r[0]??null;}
function providerApproved(p:any){return !!p && p.active===true && p.readiness_status==='READY' && p.source_tier==='A';}
async function providerSecret(name:string|null|undefined){if(!name)return null;const env=Deno.env.get(name);if(env)return env;try{const r=await sql!`select decrypted_secret from vault.decrypted_secrets where name=${name} limit 1`;return r.length?String(r[0].decrypted_secret):null;}catch{return null;}}
async function putEvidence(job:any,factClass:string,provider:string,url:string,tier:string,payload:any,status='PASS'){const fp=await sha256Hex(JSON.stringify(payload));await sql!`insert into fwios.decision_refresh_shadow_evidence(run_id,job_id,ticker,fact_class,source_provider,source_url,source_tier,observed_at,payload_fingerprint,payload,collection_status) values(${job.run_id},${job.job_id},${job.ticker},${factClass},${provider},${url},${tier},now(),${fp},${payload},${status}) on conflict(job_id,source_provider,fact_class) do update set source_url=excluded.source_url,source_tier=excluded.source_tier,observed_at=excluded.observed_at,payload_fingerprint=excluded.payload_fingerprint,payload=excluded.payload,collection_status=excluded.collection_status`;return fp;}
async function priorFingerprint(job:any,factClass:string,provider:string){const r=await sql!`select payload_fingerprint from fwios.decision_refresh_shadow_evidence where ticker=${job.ticker} and fact_class=${factClass} and source_provider=${provider} and job_id<>${job.job_id} order by created_at desc limit 1`;return r.length?String(r[0].payload_fingerprint):null;}
function compactCompanyFacts(d:any){const gaap=d?.facts?.['us-gaap']||{};const tags=['Revenues','RevenueFromContractWithCustomerExcludingAssessedTax','SalesRevenueNet','NetIncomeLoss','NetCashProvidedByUsedInOperatingActivities','PaymentsToAcquirePropertyPlantAndEquipment','CashAndCashEquivalentsAtCarryingValue','CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents','LongTermDebtCurrent','LongTermDebtNoncurrent','LongTermDebtAndFinanceLeaseObligationsCurrent','ShareBasedCompensation','StockBasedCompensation','WeightedAverageNumberOfDilutedSharesOutstanding','EarningsPerShareDiluted'];const out:Record<string,any>={};for(const tag of tags){const f=gaap?.[tag];if(!f?.units)continue;const units:Record<string,any[]>=f.units;const compact:Record<string,any[]>={};for(const [unit,rows] of Object.entries(units)){if(!Array.isArray(rows))continue;compact[unit]=rows.slice().sort((a:any,b:any)=>String(b.filed||'').localeCompare(String(a.filed||''))).slice(0,12).map((x:any)=>({val:x.val,fy:x.fy,fp:x.fp,form:x.form,filed:x.filed,start:x.start,end:x.end,frame:x.frame,accn:x.accn}));}out[tag]={label:f.label,description:f.description,units:compact};}return{entity_name:d?.entityName??null,cik:d?.cik??null,facts:out};}
async function processSec(job:any){const m=await secMap();const cik=m.get(String(job.ticker).toUpperCase());if(!cik)return{status:'BLOCKED',reason:'SEC_CIK_NOT_FOUND'};await new Promise(r=>setTimeout(r,250));const submissionsUrl=`https://data.sec.gov/submissions/CIK${cik}.json`;const factsUrl=`https://data.sec.gov/api/xbrl/companyfacts/CIK${cik}.json`;const headers={"User-Agent":SEC_UA,"Accept-Encoding":"gzip, deflate"};const [d,cf]=await Promise.all([fetchJson(submissionsUrl,headers),fetchJson(factsUrl,headers)]);const r=d?.filings?.recent||{};const forms=Array.isArray(r.form)?r.form:[];const allowed=new Set(['10-K','10-Q','8-K','20-F','40-F','6-K']);const filings:any[]=[];for(let i=0;i<forms.length&&filings.length<30;i++){if(!allowed.has(String(forms[i])))continue;filings.push({form:forms[i],accession_number:r.accessionNumber?.[i],filing_date:r.filingDate?.[i],report_date:r.reportDate?.[i],accepted_at:r.acceptanceDateTime?.[i],primary_document:r.primaryDocument?.[i],items:r.items?.[i]});}const submissions={cik,entity_name:d?.name??null,latest_filings:filings};const facts=compactCompanyFacts(cf);const p1=await priorFingerprint(job,'SEC_SUBMISSIONS','SEC_EDGAR');const p2=await priorFingerprint(job,'SEC_COMPANY_FACTS','SEC_EDGAR');const f1=await putEvidence(job,'SEC_SUBMISSIONS','SEC_EDGAR',submissionsUrl,'A',submissions);const f2=await putEvidence(job,'SEC_COMPANY_FACTS','SEC_EDGAR',factsUrl,'A',facts);return{status:'PASS',cik,latest_filing:filings[0]??null,companyfacts_tag_count:Object.keys(facts.facts||{}).length,submissions_changed:p1?p1!==f1:null,companyfacts_changed:p2?p2!==f2:null};}
function latestCommonPrice(td:any,av:any,sessionDate:string){const tdRows=Array.isArray(td?.values)?td.values:[];const avRows=av?.['Time Series (Daily)']||{};for(const row of tdRows){const d=String(row.datetime||'').slice(0,10);if(!d||d>sessionDate||!avRows[d])continue;const p1=Number(row.close),p2=Number(avRows[d]?.['4. close']);if(Number.isFinite(p1)&&Number.isFinite(p2)&&p1>0&&p2>0)return{date:d,twelve:p1,alpha:p2,tdMeta:td.meta??{}};}return null;}
async function processPrice(job:any){const td=await providerState('TWELVE_DATA'),av=await providerState('ALPHA_VANTAGE');const tdKey=await providerSecret(td?.secret_name),avKey=await providerSecret(av?.secret_name);if(!tdKey||!avKey||!providerApproved(td)||!providerApproved(av))return{status:'BLOCKED',reason:'BLOCKED_PROVIDER_NOT_CONFIGURED_OR_APPROVED',twelve_data:{secret:!!tdKey,state:td},alpha_vantage:{secret:!!avKey,state:av}};const sessionDate=String(job.session_date);const tdEnd=`${sessionDate}T23:59:59`;const turl=`https://api.twelvedata.com/time_series?symbol=${encodeURIComponent(job.ticker)}&interval=1day&outputsize=10&adjust=none&end_date=${encodeURIComponent(tdEnd)}&apikey=${encodeURIComponent(tdKey)}`;const aurl=`https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=${encodeURIComponent(job.ticker)}&outputsize=compact&apikey=${encodeURIComponent(avKey)}`;const [t,a]=await Promise.all([fetchJson(turl),fetchJson(aurl)]);if(t?.status==='error')throw new Error(`TWELVE_DATA_${t?.code||'ERROR'}`);if(a?.Note||a?.Information||a?.['Error Message'])throw new Error('ALPHA_VANTAGE_LIMIT_OR_ERROR');const px=latestCommonPrice(t,a,sessionDate);if(!px)return{status:'BLOCKED',reason:'NO_COMMON_COMPLETED_SESSION'};const div=Math.abs(px.twelve-px.alpha)/((px.twelve+px.alpha)/2);await putEvidence(job,'MARKET_PRICE','TWELVE_DATA','https://api.twelvedata.com/time_series','A',{session_date:px.date,close:px.twelve,adjust:'none',requested_end_date:tdEnd,meta:px.tdMeta});await putEvidence(job,'MARKET_PRICE','ALPHA_VANTAGE','https://www.alphavantage.co/query?function=TIME_SERIES_DAILY','A',{session_date:px.date,close:px.alpha,semantics:'raw_as_traded'});if(div>0.005)return{status:'BLOCKED',reason:'PRICE_CONFLICT',session_date:px.date,divergence_pct:div,twelve:px.twelve,alpha:px.alpha};return{status:'PASS',session_date:px.date,divergence_pct:div,selected_price:(px.twelve+px.alpha)/2,twelve:px.twelve,alpha:px.alpha,semantics:'RAW_AS_TRADED_BOTH_PROVIDERS'};}
async function processConsensus(job:any){const av=await providerState('ALPHA_VANTAGE');const key=await providerSecret(av?.secret_name);if(!key||!providerApproved(av))return{status:'BLOCKED',reason:'BLOCKED_PROVIDER_NOT_CONFIGURED_OR_APPROVED',alpha_vantage:{secret:!!key,state:av}};const url=`https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES&symbol=${encodeURIComponent(job.ticker)}&apikey=${encodeURIComponent(key)}`;const d=await fetchJson(url);if(d?.Note||d?.Information||d?.['Error Message'])throw new Error('ALPHA_VANTAGE_LIMIT_OR_ERROR');await putEvidence(job,'ANALYST_CONSENSUS','ALPHA_VANTAGE','https://www.alphavantage.co/query?function=EARNINGS_ESTIMATES','A',d);return{status:'PASS',provider:'ALPHA_VANTAGE',captured:true};}
async function handle(job:any){if(job.job_type==='SEC_SUBMISSIONS')return await processSec(job);if(job.job_type==='PRICE_PAIR')return await processPrice(job);if(job.job_type==='CONSENSUS')return await processConsensus(job);return{status:'BLOCKED',reason:'UNKNOWN_JOB_TYPE'};}
async function ack(msgId:any){await sql!`select pgmq.delete(${QUEUE}::text,${msgId}::bigint)`;}
async function archive(msgId:any){await sql!`select pgmq.archive(${QUEUE}::text,${msgId}::bigint)`;}

Deno.serve(async(req:Request)=>{if(!sql||!dbUrl)return Response.json({error:'DB_UNAVAILABLE'},{status:503});if(req.method!=='POST')return new Response('Method Not Allowed',{status:405});const token=req.headers.get('x-fwios-automation-token')||'';if(token.length<32)return new Response('Unauthorized',{status:401});const x=await sql`select token_sha256 from fwios.decision_refresh_automation_access where access_key='DECISION_REFRESH_WORKER' and active=true limit 1`;if(!x.length||!safeEqual(await sha256Hex(token),String(x[0].token_sha256)))return new Response('Unauthorized',{status:401});const messages=await sql`select * from pgmq.read(${QUEUE}::text,300::integer,10::integer)`;let passed=0,blocked=0,retried=0,dead=0;const touched=new Set<string>();for(const msg of messages){const jobId=msg?.message?.job_id;if(!jobId){await ack(msg.msg_id);continue;}const rows=await sql`select j.*,r.session_date from fwios.decision_refresh_jobs j join fwios.decision_refresh_runs r on r.run_id=j.run_id where j.job_id=${jobId}::uuid limit 1`;if(!rows.length){await ack(msg.msg_id);continue;}const job:any=rows[0];touched.add(String(job.run_id));if(['PASS','BLOCKED','DEAD_LETTER'].includes(String(job.status))){await ack(msg.msg_id);continue;}const attempt=Number(job.attempts||0)+1;await sql`update fwios.decision_refresh_jobs set status='RUNNING',attempts=${attempt},started_at=coalesce(started_at,now()),updated_at=now() where job_id=${job.job_id}::uuid`;try{const result:any=await handle(job);if(result.status==='PASS'){await sql`update fwios.decision_refresh_jobs set status='PASS',output=${result},last_error=null,completed_at=now(),updated_at=now() where job_id=${job.job_id}::uuid`;passed++;}else{await sql`update fwios.decision_refresh_jobs set status='BLOCKED',output=${result},last_error=${result.reason||null},completed_at=now(),updated_at=now() where job_id=${job.job_id}::uuid`;blocked++;}await ack(msg.msg_id);}catch(e){const err=e instanceof Error?e.message:String(e);if(attempt>=Number(job.max_attempts||5)){await sql`update fwios.decision_refresh_jobs set status='DEAD_LETTER',last_error=${err},completed_at=now(),updated_at=now() where job_id=${job.job_id}::uuid`;await archive(msg.msg_id);dead++;}else{await sql`update fwios.decision_refresh_jobs set status='RETRY',last_error=${err},updated_at=now() where job_id=${job.job_id}::uuid`;retried++;}}}for(const runId of touched)await sql`select fwios.refresh_decision_refresh_run_status(${runId}::uuid)`;return Response.json({ok:true,worker:'decision-refresh-worker-v1',version:5,read:messages.length,passed,blocked,retried,dead,mode:'SHADOW',authoritative_write:false,price_semantics:'RAW_AS_TRADED_BOTH_PROVIDERS'});});
